import 'cardatamodel.dart';
import 'package:flutter/material.dart';

List<CarDataModel> cardListData = [
  CarDataModel(
    imageUrl: 'discover.png',
    title: 'KICKS™',
    company: 'Nissan',
    price: '18,640',
    cardColor: Colors.grey[500],
    heroTag: 'discover',
    isWhite: true,
    fontColor: Colors.white,
    heroCard:'kicks', 
    category: 'mpv',
    mesinModel: '4 HK1-TCC',
    mesinTipe: 'In-line 4 Cylinders, Direct Injection Diesel, OHC',
    mesinDiameter: '115 X 125 mm',
    mesinSilinder: '5,193 cc',
    mesinTenagaMax: '190 / 2,600 PS/rpm',
    mesinTorsiMax: '52 / 1,600 – 2,600 Kgm/rpm',
    dimensiPanjang: '4.825 mm',
    dimensiLebar: '1,860 mm',
    dimensiTinggi: '1,840 mm',
    dimensiJarakSumbu: '2.845	mm',
    dimensiJarakTanah: '230 mm',
    dimensiTempatDuduk: '7 Orang',
    dimensiKapasitasTangki: '65 Liter',
    dimensiRadiusPutar: '5,8 m',
    beratKosong: '5,8 m',
    beratTotal: '5,8 m',
    transmisiModel: '',
    transmisiTipe: '',
    transmisiSistem: '',
    transmisiGigi1: '',
    transmisiGigi2: '',
    transmisiGigi3: '',
    transmisiGigi4: '',
    transmisiGigi5: '',
    transmisiRev: '',
    transmisiGigiTerakhir: '',
    banDepan: '',
    banBelakang: '',
    velg: '',
    velgWarna: '',
    remDepan: '',
    remBelakang: '',
    suspensiDepan: '',
    suspensiBelakang: '',
    lainKapasitasTangki: '',
    lainAki: '',
    lainAlternator: '',
    lainBlower: '',
  ),
  CarDataModel(
    imageUrl: 'bmw.gif',
    title: 'BMW i8™',
    company: 'BMW',
    price: '149,900',
    cardColor: Colors.white,
    heroTag: 'image_car',
    isWhite: false,
    fontColor: Colors.black,
    heroCard: 'bmw', 
    category: 'mpv',
    mesinModel: '4 HK1-TCC',
    mesinTipe: 'In-line 4 Cylinders, Direct Injection Diesel, OHC',
    mesinDiameter: '115 X 125 mm',
    mesinSilinder: '5,193 cc',
    mesinTenagaMax: '190 / 2,600 PS/rpm',
    mesinTorsiMax: '52 / 1,600 – 2,600 Kgm/rpm',
    dimensiPanjang: '4.825 mm',
    dimensiLebar: '1,860 mm',
    dimensiTinggi: '1,840 mm',
    dimensiJarakSumbu: '2.845	mm',
    dimensiJarakTanah: '230 mm',
    dimensiTempatDuduk: '7 Orang',
    dimensiKapasitasTangki: '65 Liter',
    dimensiRadiusPutar: '5,8 m',
    beratKosong: '',
    beratTotal: '',
    transmisiModel: '',
    transmisiTipe: '',
    transmisiSistem: '',
    transmisiGigi1: '',
    transmisiGigi2: '',
    transmisiGigi3: '',
    transmisiGigi4: '',
    transmisiGigi5: '',
    transmisiRev: '',
    transmisiGigiTerakhir: '',
    banDepan: '',
    banBelakang: '',
    velg: '',
    velgWarna: '',
    remDepan: '',
    remBelakang: '',
    suspensiDepan: '',
    suspensiBelakang: '',
    lainKapasitasTangki: '',
    lainAki: '',
    lainAlternator: '',
    lainBlower: '',
  ),
  CarDataModel(
    imageUrl: 'chevrolet.png',
    title: 'Corvette™',
    company: 'Chevrolet',
    price: '65,095',
    cardColor: Colors.grey[850],
    heroTag: 'chevrolet',
    isWhite: true,
    fontColor: Colors.white,
    heroCard: 'cherv',
    category: 'mpv',
    mesinModel: '4 HK1-TCC',
    mesinTipe: 'In-line 4 Cylinders, Direct Injection Diesel, OHC',
    mesinDiameter: '115 X 125 mm',
    mesinSilinder: '5,193 cc',
    mesinTenagaMax: '190 / 2,600 PS/rpm',
    mesinTorsiMax: '52 / 1,600 – 2,600 Kgm/rpm',
    dimensiPanjang: '4.825 mm',
    dimensiLebar: '1,860 mm',
    dimensiTinggi: '1,840 mm',
    dimensiJarakSumbu: '2.845	mm',
    dimensiJarakTanah: '230 mm',
    dimensiTempatDuduk: '7 Orang',
    dimensiKapasitasTangki: '65 Liter',
    dimensiRadiusPutar: '5,8 m',
    beratKosong: '',
    beratTotal: '',
    transmisiModel: '',
    transmisiTipe: '',
    transmisiSistem: '',
    transmisiGigi1: '',
    transmisiGigi2: '',
    transmisiGigi3: '',
    transmisiGigi4: '',
    transmisiGigi5: '',
    transmisiRev: '',
    transmisiGigiTerakhir: '',
    banDepan: '',
    banBelakang: '',
    velg: '',
    velgWarna: '',
    remDepan: '',
    remBelakang: '',
    suspensiDepan: '',
    suspensiBelakang: '',
    lainKapasitasTangki: '',
    lainAki: '',
    lainAlternator: '',
    lainBlower: '',
  ),
  CarDataModel(
    imageUrl: 'aston_martin.png',
    title: 'Vantage(18)',
    company: 'Aston Martin',
    price: '149,995',
    cardColor: Colors.orange[900],
    heroTag: 'aston_martin',
    isWhite: true,
    fontColor: Colors.white,
    heroCard:'aston',
    category: 'mpv',
    mesinModel: '4 HK1-TCC',
    mesinTipe: 'In-line 4 Cylinders, Direct Injection Diesel, OHC',
    mesinDiameter: '115 X 125 mm',
    mesinSilinder: '5,193 cc',
    mesinTenagaMax: '190 / 2,600 PS/rpm',
    mesinTorsiMax: '52 / 1,600 – 2,600 Kgm/rpm',
    dimensiPanjang: '4.825 mm',
    dimensiLebar: '1,860 mm',
    dimensiTinggi: '1,840 mm',
    dimensiJarakSumbu: '2.845	mm',
    dimensiJarakTanah: '230 mm',
    dimensiTempatDuduk: '7 Orang',
    dimensiKapasitasTangki: '65 Liter',
    dimensiRadiusPutar: '5,8 m',
    beratKosong: '',
    beratTotal: '',
    transmisiModel: '',
    transmisiTipe: '',
    transmisiSistem: '',
    transmisiGigi1: '',
    transmisiGigi2: '',
    transmisiGigi3: '',
    transmisiGigi4: '',
    transmisiGigi5: '',
    transmisiRev: '',
    transmisiGigiTerakhir: '',
    banDepan: '',
    banBelakang: '',
    velg: '',
    velgWarna: '',
    remDepan: '',
    remBelakang: '',
    suspensiDepan: '',
    suspensiBelakang: '',
    lainKapasitasTangki: '',
    lainAki: '',
    lainAlternator: '',
    lainBlower: '',
  ),
  CarDataModel(
    imageUrl: 'lamborghini.png',
    title: 'Urus',
    company: 'Lamborghini',
    price: '203,674',
    cardColor: Colors.red[900],
    heroTag: 'lamborghini',
    isWhite: true,
    fontColor: Colors.white,
    heroCard: 'lambor',
    category: 'mpv',
    mesinModel: '4 HK1-TCC',
    mesinTipe: 'In-line 4 Cylinders, Direct Injection Diesel, OHC',
    mesinDiameter: '115 X 125 mm',
    mesinSilinder: '5,193 cc',
    mesinTenagaMax: '190 / 2,600 PS/rpm',
    mesinTorsiMax: '52 / 1,600 – 2,600 Kgm/rpm',
    dimensiPanjang: '4.825 mm',
    dimensiLebar: '1,860 mm',
    dimensiTinggi: '1,840 mm',
    dimensiJarakSumbu: '2.845	mm',
    dimensiJarakTanah: '230 mm',
    dimensiTempatDuduk: '7 Orang',
    dimensiKapasitasTangki: '65 Liter',
    dimensiRadiusPutar: '5,8 m',
    beratKosong: '',
    beratTotal: '',
    transmisiModel: '',
    transmisiTipe: '',
    transmisiSistem: '',
    transmisiGigi1: '',
    transmisiGigi2: '',
    transmisiGigi3: '',
    transmisiGigi4: '',
    transmisiGigi5: '',
    transmisiRev: '',
    transmisiGigiTerakhir: '',
    banDepan: '',
    banBelakang: '',
    velg: '',
    velgWarna: '',
    remDepan: '',
    remBelakang: '',
    suspensiDepan: '',
    suspensiBelakang: '',
    lainKapasitasTangki: '',
    lainAki: '',
    lainAlternator: '',
    lainBlower: '',
  )

];